### ISSUE TITLE
Write warning and errors to a log file

### ISSUE THREAD

**Issue by Seekfried** [Seekfried/friedybot-d2irc#25]
If it will be deployed as a container, it's better standard output.

**Comment by nauar** [comment]
Tasks:
- Control the printable log level with a feature flag/environment variable.
- Move all the info logs to debug logs.
More info about logging levels: https://docs.python.org/3/library/logging.html#logging-levels

**Comment by nauar** [comment]
Added timestamp and colors to the logs:

![image](https://github.com/user-attachments/assets/d387ac7d-3917-4bd2-ad5d-44e9e7ea0c2c)

**Comment by nauar** [comment]
Pending to decide:
1. With this new format, should we still move the log level to WARNING or keep it at INFO?
2. Should we keep a streaming log? If it runs in a container, it makes sense to keep it.

**Comment by Seekfried** [comment]
I really like the new format.

1. I would say keep it INFO until version 1.0 then WARNING
2. With streaming log you mean the bridged messages?

**Comment by nauar** [comment]
> I would say keep it INFO until version 1.0 then WARNING

Agreed!

> With streaming log you mean the bridged messages?

I mean keeping the logs in stdout and stderr channels instead of writing them in files. It's the de facto standard in containers. In complex setups, you can put an EFK or ELK stack (for instance) to manage the logs as you want (not needed here, though).

**Comment by Seekfried** [comment]
If that is the best for container, then I will agree.
